const I18N = {
  id: { topLeft: "Rumah dagang sarang walet · Indonesia", hotel: "Hotel bintang lima", direct: "Meja langsung", importer: "Importir", home: "Rumah", collection: "Koleksi", price: "Harga", origin: "Asal-usul", about: "Tentang", ctaAlloc: "Ajukan alokasi", eyebrow: "Indonesia · Walet rumah Aerodramus fuciphagus", heroTitle: "Dari rumah walet ke meja hotel bintang lima.", heroLead: "Omniworld adalah rumah dagang sarang walet Indonesia — dinilai, didokumentasikan, dan dialokasikan untuk dapur hotel, meja pribadi, serta importir di Tiongkok dan Hong Kong.", seeCollection: "Lihat koleksi", weeklyPrice: "Harga sarang minggu ini", pathKicker: "Jalur pasok", pathTitle: "Jalur pasok yang tenang untuk barang yang mahal.", pathLead: "Kami membeli dari rumah walet terdaftar, membersihkan di ruang terkendali, dan mengirim lot yang bisa diterima steward hotel maupun importir Shenzhen.", buyKicker: "Tiga meja", buyTitle: "Satu rumah. Tiga cara membeli.", h1t: "Hospitality", h1s: "Hotel bintang lima", h1p: "Mangkuk dan serpih siap dapur, gram yang konsisten, briefing chef, berkas HACCP.", h2t: "Klien pribadi", h2s: "Meja langsung", h2p: "Mangkuk utuh dan hadiah maison, catatan keaslian, lot kolektor musiman.", h3t: "Tiongkok · Hong Kong", h3s: "Importir", h3p: "Lot berorientasi CIQ, disiplin nitrit, vakum, MOQ grosir, meja dwibahasa.", boardKicker: "Papan dagang", boardTitle: "Lot di meja bulan ini.", gradeKicker: "Grade rumah", gradeTitle: "Mangkuk, serpih, hadiah, lot ekspor.", chainKicker: "Asal-usul", chainTitle: "Rumah, tangan, dan kertas.", ctaTitle: "Sebut dapur, hadiah, atau pelabuhan.", ctaLead: "Formulirnya satu halaman. Meja membalas dengan grade, volume, dan waktu kirim.", footer: "Omniworld · PT Omni World · Jakarta", visits: "Kunjungan tercatat", stats: "Statistik" },
  en: { topLeft: "Bird's nest trading house · Indonesia", hotel: "Five-star hotels", direct: "Private table", importer: "Importers", home: "Home", collection: "Collection", price: "Prices", origin: "Provenance", about: "About", ctaAlloc: "Request allocation", eyebrow: "Indonesia · House nest Aerodramus fuciphagus", heroTitle: "From the swiftlet house to the five-star table.", heroLead: "Omniworld is an Indonesian edible bird's nest trading house — graded, documented, and allocated for hotel kitchens, private tables, and importers in China and Hong Kong.", seeCollection: "View collection", weeklyPrice: "This week's prices", pathKicker: "Supply path", pathTitle: "A quiet supply path for an expensive good.", pathLead: "We buy from registered houses, clean in controlled rooms, and ship lots that hotel stewards and Shenzhen importers can accept.", buyKicker: "Three desks", buyTitle: "One house. Three ways to buy.", h1t: "Hospitality", h1s: "Five-star hotels", h1p: "Kitchen-ready cups and strips, consistent grams, chef briefing, HACCP files.", h2t: "Private clients", h2s: "Direct table", h2p: "Whole cups and maison gifts, authenticity notes, seasonal collector lots.", h3t: "China · Hong Kong", h3s: "Importers", h3p: "CIQ-oriented lots, nitrite discipline, vacuum pack, wholesale MOQ, bilingual desk.", boardKicker: "Trade board", boardTitle: "Lots on the table this month.", gradeKicker: "House grades", gradeTitle: "Cups, strips, gifts, export lots.", chainKicker: "Provenance", chainTitle: "House, hand, and paper.", ctaTitle: "Name the kitchen, the gift, or the port.", ctaLead: "One-page form. The desk replies with grade, volume, and ship window.", footer: "Omniworld · PT Omni World · Jakarta", visits: "Recorded visits", stats: "Statistics" },
  zh: { topLeft: "印尼燕窝商行", hotel: "五星酒店", direct: "私人采购", importer: "进口商", home: "首页", collection: "品级", price: "价格", origin: "溯源", about: "关于", ctaAlloc: "申请配额", eyebrow: "印度尼西亚 · 屋燕 Aerodramus fuciphagus", heroTitle: "从燕屋到五星餐桌。", heroLead: "Omniworld 是印尼燕窝商行 — 分级、建档、配额，服务酒店厨房、私人餐桌以及中国与香港进口商。", seeCollection: "查看品级", weeklyPrice: "本周参考价", pathKicker: "供应链", pathTitle: "贵重货物需要安静的供应链。", pathLead: "我们从登记燕屋收购，在受控空间清理，并交付酒店与深圳进口商可接受的批次。", buyKicker: "三张桌子", buyTitle: "一家商行，三种买法。", h1t: "酒店", h1s: "五星厨房", h1p: "即用碗盏与厨用碎燕、克重稳定、厨师说明、HACCP 文件。", h2t: "私人客户", h2s: "直购", h2p: "完整盏形、礼盒、真伪说明与季节性收藏批次。", h3t: "中国 · 香港", h3s: "进口商", h3p: "面向 CIQ 的批次、亚硝酸盐纪律、真空包装、批发起订、双语对接。", boardKicker: "本月货盘", boardTitle: "本月在案批次。", gradeKicker: "屋燕品级", gradeTitle: "盏、碎燕、礼盒、出口批次。", chainKicker: "溯源", chainTitle: "燕屋、手工、文件。", ctaTitle: "说明厨房、礼赠或口岸。", ctaLead: "一页表格。我们回复品级、数量与交期。", footer: "Omniworld · PT Omni World · 雅加达", visits: "已记录访问", stats: "统计" }
};
function applyLang(lang) {
  const dict = I18N[lang] || I18N.id;
  document.querySelectorAll("[data-i]").forEach((el) => {
    const key = el.getAttribute("data-i");
    if (dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll(".lang button").forEach((b) => {
    b.classList.toggle("active", b.dataset.lang === lang);
  });
  document.documentElement.lang = lang === "zh" ? "zh-CN" : lang;
  localStorage.setItem("ow_lang", lang);
}
document.addEventListener("DOMContentLoaded", () => {
  applyLang(localStorage.getItem("ow_lang") || "id");
  document.querySelectorAll(".lang button").forEach((b) => {
    b.addEventListener("click", () => applyLang(b.dataset.lang));
  });
});
